### ISSUE TITLE
No Egg or Cooked Egg Recipes under Discovery Tab

### ISSUE THREAD

**Issue by antzpantz** [bluehexagons/foodguide#11]
Under the Discovery tab, if you click on Egg or Cooked Egg, no recipes are given. Not much else to say here. Using Chrome Version 52.0.2743.116 m (64-bit)

**Comment by bluehexagons** [comment]
It doesn't look like any recipes can be made with only eggs. The Discovery tab only considers recipes you can put together with the ingredients you give it, so if you've only added eggs the only thing you can make is goop.

**Comment by antzpantz** [comment]
Ahh ok, sorry. I misunderstood how it works. I thought selecting at least one ingredient would show what recipes you can make with that which would then narrow it down as you select more ingredients.

**Comment by bluehexagons** [comment]
You can basically do that using the simulator, it'll suggest recipes that specifically any of the ingredients you've added so far. It's not incredibly smart. You can also go to the food list and click on the "Recipes" button in the Info column to highlight the recipes it's used in. I hope that's helpful.

**Comment by antzpantz** [comment]
Ahh Excellent! I hadn't used the simulator, so I didn't know it suggested recipes on the fly. Thank you!
