### ISSUE TITLE
Values in brackets in food list has no explanation anywhere

### ISSUE THREAD

**Issue by GEULACH** [bluehexagons/foodguide#18]
Example: Cactus Flesh	-3 (+4)	+12.5	-5 (+20)

What does (+4) and (+20) even mean? no explanation in help section either.

**Comment by bluehexagons** [comment]
Those are the stat changes when the item gets cooked. I'm not sure why I didn't add a tooltip or something somewhere to describe what that means, since it's not immediately obvious. Also seems like it'd be really useful to include that for perish times as well.

**Comment by bluehexagons** [comment]
This is now explained in hover text like it should have been to begin with.
