### ISSUE TITLE
Wrong fish/value for cooked fish

### ISSUE THREAD

**Issue by Parusoid** [bluehexagons/foodguide#24]
Cooked Fish (cooked fish morsel) should have 0.5 x fish value, but in here it has 1 x fish AND 0.5 x meat which is wrong and is messing up the simulator recipes

**Comment by bluehexagons** [comment]
Cooked Fish Morsel seems to already have a 0.5x fish value. Regular Cooked Fish has the same values currently listed for it on the wiki (1x fish, 0.5x meat). Are you maybe choosing the wrong item? Do you have Shipwrecked DLC enabled in the Food Guide to see the Morsel versions?

**Comment by bluehexagons** [comment]
I actually hadn't noticed the icons were different at all until you said they were only similar, so that's understandable.
