### ISSUE TITLE
https://bluehexagons.com/foodguide/ returns 403 forbidden

### ISSUE THREAD

**Issue by rezecib** [bluehexagons/foodguide#38]
Not an issue with the source here, but just so you know, in case you have the time to fix it.

I've redirected people to the github.io page (https://bluehexagons.github.io/foodguide/html/index.htm) for now, as that still loads.

Edit: Ah, I checked from the root page and see your site now redirects to github.io as well, so I guess that was intended?

**Comment by bluehexagons** [comment]
Messed up some nginx configuration, so not intentional. I didn't notice because of what you pointed out, I never updated the link on my own website to go to my copy. Really smart of me.

Should all be fixed now. Thanks for pointing this out to me!
