### ISSUE TITLE
Missing newest recipes from Reap What You Sow

### ISSUE THREAD

**Issue by cbooker1** [bluehexagons/foodguide#39]
Newest update in DST Reap What You Sow includes new weeds/plants allowed in the crock pot. There's also some older recipes that may be missing from the simulator.

https://dontstarve.fandom.com/wiki/Reap_What_You_Sow

Mostly making this issue as I consider how I would implement updates, unsure at this time.

**Comment by bluehexagons** [comment]
Addressed in PR #45
