### ISSUE TITLE
jerky health values

### ISSUE THREAD

**Issue by ungoliant** [bluehexagons/foodguide#4]
the health bonus calculations in the new system are thrown way off by treating uncooked versions of morsels, meat, fish, tropical fish(possibly others?) as their jerky counterparts.

as an example, a surf and turf recipe of Fish, Fish, Frog Legs, Meat yields a health bonus of +23 in the current system, where it should really be calculated as +54

**Comment by bluehexagons** [comment]
This seems reasonable to me. Idealized stats no longer use dried versions. While I was at it, I changed the parenthesis value for raw foods in food tables to show a difference once cooked, since that's more useful than knowing what the best value for the food is without context.
