### ISSUE TITLE
Link recipes in "Discovery" tab with entries in "Recipe list" tab

### ISSUE THREAD

**Issue by g102** [bluehexagons/foodguide#44]
It'd be nice if there were a link in the recipes shown in the "Discovery" tab, under "Info" for a given food, and the corresponding recipe in the "Recipe list" tab.

Something similar is already implemented for the tab "Food list", where clicking on a recipe under Info moves the user to the "Recipe list" tab and highlights the selected recipe.

**Comment by bluehexagons** [comment]
I added a first pass on this that has the tags link to the food/recipe lists, but a follow-up change could add the option to search instead.
