### ISSUE TITLE
Didn't get Guacamole recipe

### ISSUE THREAD

**Issue by FogyX** [bluehexagons/foodguide#56]
Moleworm + Ripe Stone Fruit + 2 Twigs = Wet Goop

DST filter is on, so I think it is a bug

**Comment by FogyX** [comment]
![image](https://github.com/bluehexagons/foodguide/assets/93732719/edd128f1-e490-4928-96a4-36605bca9e79)

**Comment by bluehexagons** [comment]
Seems to be working now.
