### ISSUE TITLE
When choosing Recipe mode in the discovery tab, food items across different masks will show up

### ISSUE THREAD

**Issue by lakhnishMonster** [bluehexagons/foodguide#59]
Choose your mask and then choose discovery mode.
Then choose the recipe mode button and input a recipe (example: Honey Ham).
What you'll see is that food items from masks you did not select will show up as an ingredient when it shouldn't.

In this example, we have SW foods showing up when only DS + RoG + DST is selected.

![masks](https://github.com/bluehexagons/foodguide/assets/42256014/d44e65a6-706d-4444-b517-86007b1b76d7)

**Comment by bluehexagons** [comment]
All of the filters should filter by mode with that commit.
