### ISSUE TITLE
Mushrooms

### ISSUE THREAD

**Issue by eddebaby** [bluehexagons/foodguide#8]
It looks like the Raw and Cooked Mushrooms in the Simulator tab do not have their values displayed correctly in the "Combined" row of the table. It looks like it is using some stats for the cooked and some for the raw.

**Comment by bluehexagons** [comment]
This is actually intended, at least for raw mushrooms. If something can be cooked, it'll use the better values when calculating the combined amount. If cooked is different, then that's probably a bug.

**Comment by MidrealmDM** [comment]
The simulator shows the following for Red Mushroom: 
0.9, 8.75, 0 
Actual Values
Raw: -20, 12.5, 0
Cooked: 1, 0, -10

So I'm not sure where the simulator is pulling it's numbers from.
Same is true for Green and Blue, the numbers don't match Cooked or Raw.
The numbers appear to be between +/- 10% to +/- 30% of the true values.

**Comment by bluehexagons** [comment]
@MidrealmDM I'm not seeing this at all. What tab are you seeing these numbers on? Are you definitely on https://bluehexagons.github.io/foodguide/html/index.htm and not a fork or something? Is what you're seeing related to the issue you've commented on (as in, on the "combined" row)?

**Comment by MidrealmDM** [comment]
Ok - umm no, I was at  this site
https://rezecib.github.io/foodguide/html/index.htm

very odd indeed, the link you provided shows the accurate food values.
I will be changing my bookmark, thank you.

**Comment by MidrealmDM** [comment]
Hrmm - Actually they still show incorrect values.

![capture3](https://cloud.githubusercontent.com/assets/22008098/18259120/18427916-73a6-11e6-9cac-057e4cb6762d.PNG)
![capture1](https://cloud.githubusercontent.com/assets/22008098/18259119/184090ba-73a6-11e6-898c-50c203aeb43e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/22008098/18259118/183fdb2a-73a6-11e6-94a6-762006b14dcf.PNG)

**Comment by bluehexagons** [comment]
Ah, I've figured it out. It looks like you're viewing the guide as Warly. I didn't think of it at first because I haven't played since before the first expansion came out, the guide's only up to date with Shipwrecked thanks to rezecib. In the top-left of the guide, left-click on the icon for the version of the game that you're playing or right-click on Warly.

**Comment by MidrealmDM** [comment]
Lol - yep - I had toggled him on last time I visited, didn't realize it saved the setting.
Sorry to bother you.
^_^
